---
# tasks file for pushtos3
- name: "basic upload"
  community.aws.s3_sync:
    bucket: locoust-csv-files
    file_root: roles/s3/files/
- name: "all the options"
  community.aws.s3_sync: 
    bucket: locoust-csv-files
    file_change_strategy: force
    file_root: roles/s3/files
    include: ".csv"
    permission: public-read